Zabdulre/vz 5822
verrazzano/verrazzano-monitoring-operator pull request #221
Opened 2022-07-15 18:26 UTC by zabdulre

Description
-Add metric types, add metrics helper functions,
-Add metrics registration logic
-Add unit tests
-Modify go mod and licenses accordingly 

Checklist

As the author of this PR, I have:

Checked that I included or updated copyright and license notices in all files that I altered
Added or updated unit tests for any new functions I added
Added or updated integration tests if appropriate
Added or updated acceptance tests if appropriate
Code reviewer, please confirm this PR:
Addressed the requirement and meets the acceptance criteria
Does not introduce unrelated or spurious changes
Does not introduce any unapproved dependency
Makes sense and it easy to understand, and/or difficult areas of code are clearly documented so that they can be understood

2022-07-15 19:06 UTC, anders-swanson commented on go.mod
> +	github.com/pkg/errors v0.9.1
If this is no longer indirect, can you place it in the `require` block for direct dependencies?

2022-07-15 19:07 UTC, anders-swanson commented on pkg/vmo/controller.go
> +	FunctionMetricsMap["reconcile"].LogStart()
"reconcile" -> should be const value

2022-07-15 19:07 UTC, anders-swanson commented on pkg/vmo/controller.go
> +			FunctionMetricsMap["deployment"].errorTotal.metricVecErrorIncrement(FunctionMetricsMap["deployment"].GetLabel())
"deployment" -> should be const value

2022-07-15 19:08 UTC, zabdulre commented on go.mod
> +	github.com/pkg/errors v0.9.1
yes, will do

2022-07-15 19:11 UTC, anders-swanson commented on pkg/vmo/deployment.go
> +	FunctionMetricsMap["deployment"].LogStart()
Why are we only intrumenting deployment.go and controller.go?

2022-07-15 19:11 UTC, stevshap commented on pkg/vmo/deployment.go
> +			ErrorMetricMap["deploymentUpdateErrorCounter"].metricVecErrorIncrement(FunctionMetricsMap["deployment"].GetLabel())
all the map indices should be consts

2022-07-15 19:13 UTC, zabdulre commented on pkg/vmo/deployment.go
> +	FunctionMetricsMap["deployment"].LogStart()
I am adding extra metrics in the second pass. The format for the metrics will be the same

2022-07-15 19:14 UTC, zabdulre commented on pkg/vmo/deployment.go
> +			ErrorMetricMap["deploymentUpdateErrorCounter"].metricVecErrorIncrement(FunctionMetricsMap["deployment"].GetLabel())
would this const be declared in the metricsexporter.go file?

2022-07-15 19:15 UTC, anders-swanson commented on pkg/vmo/deployment.go
> +	SimpleCounterMetricMap["deploymentDeleteCounter"].metric.Inc()
Since VMO is running continuously & always reconciling these numbers will be high. Do you think they are meaningful?

2022-07-15 19:19 UTC, anders-swanson commented on pkg/vmo/metricsexporter.go
> +	index             int64
What is `index`?

2022-07-15 19:19 UTC, zabdulre commented on pkg/vmo/deployment.go
> +	SimpleCounterMetricMap["deploymentDeleteCounter"].metric.Inc()
My understanding is that the metrics will provide usage and availability insights. If the number does not increase when it is supposed to/Starts increasing rapidly, it can be a sign that something is amiss. I ran this idea by the team during the design review as well, but I am always open to any suggestions of other useful metrics

2022-07-15 19:20 UTC, anders-swanson commented on pkg/vmo/metricsexporter.go
> +type FunctionMetrics struct {
This implementation looks a lot different than George's. Was there a need to create separate implementations? From a maintenance perspective, it makes sense to keep these similar (or even share code if it is applicable).

2022-07-15 19:20 UTC, zabdulre commented on pkg/vmo/metricsexporter.go
> +	index             int64
index is the number of times a function has been called, its value is the exact same as the callsTotal metric

2022-07-15 19:22 UTC, anders-swanson commented on pkg/vmo/controller.go
> +			FunctionMetricsMap["deployment"].errorTotal.metricVecErrorIncrement(FunctionMetricsMap["deployment"].GetLabel())
I would favor a more encapsulated type call here. Compare this with something like:
```
metrics.Deployment().Errors().Increment()
```

2022-07-15 19:22 UTC, anders-swanson commented on pkg/vmo/controller.go
> +			FunctionMetricsMap["deployment"].errorTotal.metricVecErrorIncrement(FunctionMetricsMap["deployment"].GetLabel())
Internally in the metrics object it would look more like the call you have here

2022-07-15 19:24 UTC, anders-swanson commented on pkg/vmo/metricsexporter.go
> +type FunctionMetrics struct {
Was research done on existing implementations using this prometheus exporter client library?

2022-07-15 19:27 UTC, anders-swanson commented on pkg/vmo/metricsexporter.go
> +	FunctionMetricsMap = map[string]*FunctionMetrics{
Suggest to add a metrics object that is passed into the main Controller object

2022-07-15 19:28 UTC, anders-swanson commented on pkg/vmo/metricsexporter.go
> +	index             int64
Why is index separate?

2022-07-15 19:29 UTC, zabdulre commented on pkg/vmo/metricsexporter.go
> +type FunctionMetrics struct {
Yes, from my research I saw that many implementations kept the metrics very simple. Metrics were not declared at the package level, but functions to manipulate those metrics were duplicated for each metric. Im not sure how George has changed his implementation since. I did not plan my structure to be similar since my focus is on monitoring the VMO itself with a variety of metrics

2022-07-15 19:29 UTC, anders-swanson commented on pkg/vmo/metricsexporter.go
> +	labelFunction     *func(int64) string //The function to create the label values for the error and timestamp metrics. A default is provided as &DefaultLabelFunction
Why are we using a pointer to a function?

2022-07-15 19:30 UTC, zabdulre commented on pkg/vmo/metricsexporter.go
> +	FunctionMetricsMap = map[string]*FunctionMetrics{
Will look into this

2022-07-15 19:31 UTC, zabdulre commented on pkg/vmo/metricsexporter.go
> +	labelFunction     *func(int64) string //The function to create the label values for the error and timestamp metrics. A default is provided as &DefaultLabelFunction
If many declarations use the "DefaultLabelFunction" and this function is changed at some point during execution, then all declarations would use the newest version of the changed function

2022-07-15 19:32 UTC, zabdulre commented on pkg/vmo/controller.go
> +			FunctionMetricsMap["deployment"].errorTotal.metricVecErrorIncrement(FunctionMetricsMap["deployment"].GetLabel())
Gotcha, I will look into this

2022-07-15 19:32 UTC, anders-swanson commented on pkg/vmo/metricsexporter.go
> +package vmo
consider a `metrics` package or similar name

2022-07-15 19:34 UTC, zabdulre commented on pkg/vmo/metricsexporter.go
> +	index             int64
The prometheus documentation discourages reading a counter metric directly unless it is read during a unit test. I believe this issue is related to performance

2022-07-15 19:35 UTC, anders-swanson commented on pkg/vmo/metricsexporter.go
> +	durationSeconds   DurationMetric
can you rename this to `durationMetric` and the like, it makes it easier to read

2022-07-15 19:35 UTC, zabdulre commented on pkg/vmo/metricsexporter.go
> +	index             int64
It cannot be read without the testutil library

2022-07-15 19:36 UTC, zabdulre commented on pkg/vmo/metricsexporter.go
> +package vmo
That was my original intention, but I had to switch both files to the vmo package to ensure the unit tests worked (using fakes)

2022-07-15 19:36 UTC, zabdulre commented on pkg/vmo/metricsexporter.go
> +	durationSeconds   DurationMetric
will do

2022-07-15 19:38 UTC, zabdulre commented on pkg/vmo/metricsexporter.go
> +package vmo
Should I create one large "metrics" struct which contains all the metrics maps? I think this would give a similar effect

2022-07-15 19:49 UTC, anders-swanson commented on pkg/vmo/metricsexporter_test.go
> +func clearMetrics() {
You can defer this function in your tests. Still, it will not help if the test suite is run concurrently.

2022-07-15 19:51 UTC, zabdulre commented on pkg/vmo/metricsexporter_test.go
> +func clearMetrics() {
got it, I will try this

2022-07-15 19:56 UTC, davisgomes commented on pkg/vmo/deployment.go
> +			ErrorMetricMap["deploymentUpdateErrorCounter"].metricVecErrorIncrement(FunctionMetricsMap["deployment"].GetLabel())
If you use the type calls that Anders recommended, then yes, they should be in the metricsexporter.go file

2022-07-15 19:59 UTC, davisgomes commented on pkg/vmo/metricsexporter.go
> +package vmo
Are you sure you have to switch the package for fakes? You could write some test utility functions in the package if you need to get information from the metrics

2022-07-15 20:01 UTC, davisgomes commented on pkg/vmo/metricsexporter.go
> +type FunctionMetrics struct {
I agree. George's implementation has changed quite drastically after the comments. I think it would be good to make the external implementation agree as much as possible so that metrics are easy to add to each source and have similar interfaces.

2022-07-15 20:12 UTC, davisgomes commented on pkg/vmo/metricsexporter.go
> +func (thisMetric *FunctionMetrics) LogStart() {
usually Struct metrics contain one letter references:
```
func (f *FunctionMetrics) LogStart()
```

2022-07-15 20:12 UTC, davisgomes commented on pkg/vmo/metricsexporter.go
> +	FunctionMetricsMap = map[string]*FunctionMetrics{
George had done something similar

2022-07-15 20:12 UTC, davisgomes commented on pkg/vmo/metricsexporter.go
> +func (thisMetric *FunctionMetrics) GetLabel() string {
Why are we labeling the metrics?

2022-07-15 20:12 UTC, davisgomes commented on pkg/vmo/metricsexporter.go
> +func numToString(num int64) string {
There's a built in function for this `s := strconv.Itoa(num)`

2022-07-15 20:12 UTC, davisgomes commented on pkg/vmo/metricsexporter_test.go
> +func TestOneValidMetric(t *testing.T) {
There is a decent amount of duplication in these tests, you might want to look into the test loop that Raaghav and George have

2022-07-15 20:12 UTC, davisgomes commented on pkg/vmo/metricsexporter_test.go
> +func TestOneValidMetric(t *testing.T) {
It allows for faster expansion of unit test cases if you want to test a bunch of cases

2022-07-15 20:20 UTC, mbenmclean commented on pkg/vmo/deployment.go
> +		ErrorMetricMap["deploymentDeleteErrorCounter"].metricVecErrorIncrement(FunctionMetricsMap["deployment"].GetLabel())
make a constant

2022-07-15 20:20 UTC, mbenmclean commented on pkg/vmo/metricsexporter.go
> +	//Metrics can be accessed through the metrics maps. All metrics declared in the metrics maps or allmetrics array are registered automatically.
add a space after //

2022-07-15 20:20 UTC, mbenmclean commented on pkg/vmo/metricsexporter.go
> +	DefaultLabelFunction = func(index int64) string { return numToString(index) }
make multiple lines

2022-07-15 21:21 UTC, zabdulre commented on pkg/vmo/deployment.go
> +			ErrorMetricMap["deploymentUpdateErrorCounter"].metricVecErrorIncrement(FunctionMetricsMap["deployment"].GetLabel())
got it

2022-07-15 21:22 UTC, zabdulre commented on pkg/vmo/metricsexporter.go
> +	FunctionMetricsMap = map[string]*FunctionMetrics{
gotcha

2022-07-15 21:22 UTC, zabdulre commented on pkg/vmo/metricsexporter.go
> +package vmo
I will look into making the package separate again

2022-07-15 21:23 UTC, zabdulre commented on pkg/vmo/metricsexporter.go
> +func (thisMetric *FunctionMetrics) LogStart() {
ok, will do

2022-07-15 21:24 UTC, zabdulre commented on pkg/vmo/metricsexporter.go
> +func (thisMetric *FunctionMetrics) GetLabel() string {
label here is referring to the key in the metric vector. This can be something like a timestamp or the reconcile count for example

2022-07-15 21:25 UTC, zabdulre commented on pkg/vmo/deployment.go
> +		ErrorMetricMap["deploymentUpdateErrorCounter"].metricVecErrorIncrement(FunctionMetricsMap["deployment"].GetLabel())
got it

2022-07-15 21:26 UTC, zabdulre commented on pkg/vmo/metricsexporter_test.go
> +func TestOneValidMetric(t *testing.T) {
I will follow up on this after resolving structure related comments

2022-07-20 18:03 UTC, anders-swanson commented on pkg/metricsexporter/metricsexporter.go
> +package metricsExporter
lowercase is convention for package name

2022-07-20 18:03 UTC, anders-swanson commented on pkg/metricsexporter/metricsexporter.go
> +package metricsExporter
if you are curious -> https://go.dev/blog/package-names

2022-07-20 20:40 UTC, zabdulre commented on pkg/metricsexporter/metricsexporter.go
> +package metricsExporter
will do, thank you for taking a look!

2022-07-25 15:49 UTC, davisgomes commented on pkg/metricsexporter/metricsexporter.go
> +	failedMetrics map[prometheus.Collector]int //thisMetric map will be automatically populated with all metrics which were not registered correctly. Metrics in thisMetric map will be retried periodical
These comments are a bit too long to be inline, can you put them above the variables?

2022-07-25 15:52 UTC, davisgomes commented on pkg/metricsexporter/metricsexporter.go
> +	//emptyLabelFunction       = func() string { return "default" }
remove commented out code

2022-07-25 15:54 UTC, davisgomes commented on pkg/metricsexporter/metricsexporter.go
> +				errorObserved = errors.Wrap(errorObserved, err.Error())
What does this do? This seems to be the reason for the go mod changes, so I'm wondering if it is required

2022-07-25 15:56 UTC, davisgomes commented on pkg/metricsexporter/metricsexporter.go
> +				errorObserved = errors.Wrap(errorObserved, err.Error())
I think this function formatting could use some work. If you encounter an error, it seems to me that you can log it and return immediately. This also removes the need for the else statement.

2022-07-25 15:57 UTC, davisgomes commented on pkg/metricsexporter/metricsexporter.go
>  }
Can you replace all of the references to this function with `strings.atoi`?

2022-07-25 16:17 UTC, zabdulre commented on pkg/metricsexporter/metricsexporter.go
> +func (c *simpleCounterMetric) Inc() {
will do

2022-07-25 16:19 UTC, zabdulre commented on pkg/metricsexporter/metricsexporter.go
> +				errorObserved = errors.Wrap(errorObserved, err.Error())
This is to log multiple errors. It is a change Anders suggested. This way, I can avoid logging errors in the function that is called by this function

2022-07-25 16:20 UTC, zabdulre commented on pkg/metricsexporter/metricsexporter.go
>  }
working on this

2022-07-25 18:05 UTC, mbenmclean commented on pkg/metricsexporter/metricsexporter_utils.go
> +func RequiredInitialization() {
Don't love this function name but up to you.

2022-07-25 18:05 UTC, mbenmclean commented on pkg/metricsexporter/metricsexporter_utils.go
> +			zap.S().Errorf("Failed to start metrics server for VMI: %v", err)
Should this be VMO?

2022-07-25 18:14 UTC, zabdulre commented on pkg/metricsexporter/metricsexporter.go
> -			zap.S().Errorf("Failed to start metrics server for VMI: %v", err)
will change

2022-07-25 18:14 UTC, zabdulre commented on pkg/metricsexporter/metricsexporter_utils.go
> +			zap.S().Errorf("Failed to start metrics server for VMI: %v", err)
it should be vmi

2022-07-25 18:16 UTC, zabdulre commented on pkg/vmo/metricsexporter_test.go
> +func TestOneValidMetric(t *testing.T) {
Update: this will be added in a future PR

2022-07-25 18:16 UTC, zabdulre commented on pkg/metricsexporter/metricsexporter.go
> +	allMetrics    []prometheus.Collector       //thisMetric array will be automatically populated with all the metrics from each map. Metrics not included in a map can be added to thisMetric array for r
will do

2022-07-25 18:16 UTC, zabdulre commented on pkg/metricsexporter/metricsexporter.go
> +type simpleCounterMetric struct {
will do

2022-07-25 19:16 UTC, zabdulre commented on pkg/metricsexporter/metricsexporter_utils.go
> +func RequiredInitialization() {
Did not change this to make sure that the naming is consistent with other 2 exporters

2022-07-25 20:09 UTC, stevshap commented on pkg/vmo/configmap.go
> +
delete new line

2022-07-25 20:12 UTC, stevshap commented on pkg/vmo/deployment.go
> +	defer metricsexporter.GetFunctionMetrics(metricsexporter.NamesDeployment).LogEnd(false) //The error count is incremented by the function which calls createDeployment
probably put the comment before the call to metrics exporter
also put a space between "//" and "The"

2022-07-25 20:13 UTC, stevshap reviewed
Minor formatting changes, looks good otherwise

2022-07-25 22:18 UTC, anders-swanson commented on pkg/vmo/controller.go
> +	defer func() { metricsexporter.GetFunctionMetrics(metricsexporter.NamesReconcile).LogEnd(errorObserved) }()
do you need `defer func`, can you just say `defer metricsexporter.GetFunctionMetrics(metricsexporter.NamesReconcile).LogEnd(errorObserved)`

2022-07-25 22:21 UTC, anders-swanson commented on pkg/vmo/deployment.go
> +	metric, metricErr := metricsexporter.GetCounterMetrics(metricsexporter.NamesDeploymentDeleteCounter)
seems a bit duplicated because of the error handling, just to increment a metric. I understand it's that way because you don't know if the metric exists or not, but would have preferred it to look something like `metrics.CounterX.Inc()` without the extra lines

2022-07-25 22:23 UTC, anders-swanson commented on pkg/vmo/controller.go
> +			metricsexporter.GetFunctionMetrics(metricsexporter.NamesReconcile).IncError()
potential NPE anytime you do this and the metric name doesn't exist in the map

2022-07-25 22:24 UTC, anders-swanson commented on pkg/vmo/ingress.go
> +		metricsexporter.GetFunctionMetrics(metricsexporter.NamesIngress).IncError()
potential NPE for all of these, not sure why were are handling the error for some but not for others (just logging it and then panic on nil return value)

2022-07-25 22:26 UTC, anders-swanson requested changes
See comments about handling some errors vs. not handling others

2022-07-26 01:53 UTC, zabdulre commented on pkg/vmo/deployment.go
> +	metric, metricErr := metricsexporter.GetCounterMetrics(metricsexporter.NamesDeploymentDeleteCounter)
There is a workaround for this, which is to just return a dummy metric instead of nil. Not sure if this is preferred though

2022-07-26 17:31 UTC, anders-swanson approved these changes

2022-07-26 17:47 UTC, davisgomes approved these changes

2022-07-26 17:50 UTC, mbenmclean approved these changes

2022-07-26 17:51 UTC, merged