Fix for OS cluster going to yellow state in dev profile when ISM polices are enabled in VZ CR
verrazzano/verrazzano-monitoring-operator pull request #224
Opened 2022-07-26 15:31 UTC by anajosep

Fixes VZ-6538 OS cluster goes to yellow state when the hidden indices created by ISM plugin creates with replica=1 as the dev profile has a single node OS cluster. This causes one secondary node to remain assigned causing the cluster to go into yellow state.

2022-07-26 15:38 UTC, anders-swanson commented on pkg/opensearch/opensearch.go
> +		if err := o.updateDefaultIndexSettings(opensearchEndpoint); err != nil {
Should this be called in the ISM function?
Also, any concern with this being called repeatedly?

2022-07-27 13:52 UTC, anders-swanson requested changes
Please fix the linter

2022-07-28 13:41 UTC, anders-swanson approved these changes
LGTM

2022-07-28 15:06 UTC, anajosep commented on pkg/opensearch/opensearch.go
> +		if err := o.updateDefaultIndexSettings(opensearchEndpoint); err != nil {
Created a separate Go routine based function. There is no issues if this call is made repeatedly. Only this specific section of the index settings is patched and the rest of the settings are persisted.

2022-07-28 15:17 UTC, merged